env:
  name: CartPole-v1
  max_step: 500
  pomdp: False

network:
  name: gym_model
  num_state: 4
  num_action: 2
  discrete_action: True
  gru: False

strategy:
  name : openai_es
  init_sigma: 0.1
  sigma_decay: 0.999
  learning_rate: 0.01
  elite_num: 1
  offspring_num: 96
