env:
  name: LunarLanderContinuous-v2
  max_step: 300
  pomdp: True

network:
  name: gym_model
  num_state: 8
  num_action: 4
  discrete_action: False
  gru: True

strategy:
  name : openai_es
  init_sigma: 0.168
  sigma_decay: 0.9999
  learning_rate: 0.087
  offspring_num: 96