offspring_strategy:
  _target_: learning_strategies.evolution.offspring_strategies.simple_evolution
  init_sigma: ${init_sigma}
  sigma_decay: ${sigma_decay}
  elite_num: ${elite_num}
  offspring_num: ${offspring_num}
  sigma_decay_method: ${sigma_decay_method}
env: 
  _target_: envs.pettingzoo_wrapper.PettingzooWrapper
  env_name: multiwalker
  max_step: 500
network:
  _target_: networks.neural_network.GymEnvModel
  num_state: 31
  num_action: 4
  discrete_action: False
  gru: ${gru}

cpu_num: 11
generation_num: 500
eval_ep_num: 3
log: False

init_sigma: 3
sigma_decay: 0.999
elite_num: 10
offspring_num: 286
sigma_decay_method: simple_decay
gru: False