env:
  name: PongNoFrameskip-v4
  max_step: None
  pomdp: False

network:
  name: AtariDQN
  num_channel: 4
  num_action: 6

strategy:
  name : openai_es
  init_sigma: 0.168
  sigma_decay: 0.9999
  learning_rate: 0.087
  offspring_num: 96