env:
  name: simple_spread
  max_step: None

network:
  name: gym_model
  num_state: 18
  num_action: 5
  discrete_action: True
  gru: True

strategy:
  name : openai_es
  init_sigma: 0.2
  sigma_decay: 0.9999
  learning_rate: 0.05
  offspring_num: 96