env:
  name: simple_spread
  max_step: None

network:
  name: gym_model
  num_state: 12
  num_action: 5
  discrete_action: True
  gru: False

strategy:
  name : openai_es
  init_sigma: 0.2
  sigma_decay: 0.99999
  learning_rate: 0.1
  offspring_num: 240